% generating movie of Heatmap of Front Properties

dphidr = zeros(soln1D.simul.nx,4,2);
phimovvid = VideoWriter([postproc.folderloc1D,'/Terms_GDE.avi']);	
open(phimovvid);
figl  =	figure('position',[100,35,1250,700],'visible',postproc.vistogmov);
if (soln1D.geomdom.isradial ~= 0)
	axl = axes(figl,'position',[0.125,0.125,0.80,0.325]); hold on;
	axllin = axes(figl,'position',[0.125,0.600,0.80,0.35]); hold on;
else
	axl = axes(figl,'position',[0.125,0.15,0.85,0.800]); hold on;
end
if (soln1D.geomdom.isradial ~= 0)
	set(axllin,'box','on'); grid(postproc.gridtog); set(axllin,'fontsize',25);set(axllin,'ticklabelinterpreter','latex');
end
set(axl,'box','on'); grid(postproc.gridtog); set(axl,'fontsize',25);set(axl,'ticklabelinterpreter','latex');
if (soln1D.geomdom.isradial == 0)
	xliml =			0.0;
	xlimr =			soln1D.geomdom.size.Lx;
else
	xliml =			max([soln1D.geomdom.size.a,postproc.maxxrange_log*soln1D.geomdom.size.A]);
	xlimr =			soln1D.geomdom.size.A;
end
if (soln1D.geomdom.isradial ~= 0)
	set(axllin,'xlim',[soln1D.geomdom.size.a,soln1D.geomdom.size.A]);
end
set(axl,'xlim',[xliml,xlimr]);
if (soln1D.geomdom.isradial ~= 0)
	set(axl,'xscale','log');
end
set(axl,'yscale','log');
if (soln1D.geomdom.isradial ~= 0)
	set(axllin,'yscale','log');
end
set(axl,'ylim',[1E-10,1E10]);
if (soln1D.geomdom.isradial ~= 0)
	set(axllin,'ylim',[1E-10,1E10]);
end
if (soln1D.geomdom.isradial == 0)
	xlabel('$x$','interpreter','latex');
else
	xlabel('$r$','interpreter','latex');
end
ylabel('GDE termss','interpreter','latex');
% plotting regime switches
plot(axl,[xliml,xlimr],[0,0],'k:','linewidth',1);
plot(axl,	...
min(xlimr,((soln1D.fltr.eta*soln1D.fltr.nondim.Pe)^(1/double(soln1D.geomdom.isradial))))*[1,1],	...
[-1.25,1.25],'--','color',[0.2,0.9,0.9],'linewidth',2);
% plotting on linear axis
if (soln1D.geomdom.isradial ~= 0)
	plot(axllin,[xliml,xlimr],[0,0],'k:','linewidth',1);
	plot(axllin,	...
	min(xlimr,((soln1D.fltr.eta*soln1D.fltr.nondim.Pe)^(1/double(soln1D.geomdom.isradial))))*[1,1],...
	[-1.25,1.25],'--','color',[0.2,0.9,0.9],'linewidth',2);
end
ifront.tsaved = 0;
for it = soln1D.simul.tstepsave
	try
		ifront.tsaved =								ifront.tsaved+1;
%		accumulating numerical solutions
		phiCcurrent =		load([postproc.folderloc1D,'/phiC_',num2str(it),'.dat']);
		phiAcurrent =		load([postproc.folderloc1D,'/phiA_',num2str(it),'.dat']);
		phiBcurrent =		load([postproc.folderloc1D,'/phiB_',num2str(it),'.dat']);
		phiAmBcurrent =	phiAcurrent-phiBcurrent;
		ix = 1;
		dphidr(ix,1,1) =			differentiation(phiAcurrent,soln1D.grd.x,ix,1,'fd',postproc.derivwarn);
		dphidr(ix,2,1) =			differentiation(phiBcurrent,soln1D.grd.x,ix,1,'fd',postproc.derivwarn);
		dphidr(ix,3,1) =			differentiation(phiCcurrent,soln1D.grd.x,ix,1,'fd',postproc.derivwarn);
		dphidr(ix,4,1) =			differentiation(phiAmBcurrent,soln1D.grd.x,ix,1,'fd',postproc.derivwarn);
		for ix = 2:soln1D.simul.nx-1
			dphidr(ix,1,1) =		differentiation(phiAcurrent,soln1D.grd.x,ix,1,'cd',postproc.derivwarn);
			dphidr(ix,2,1) =		differentiation(phiBcurrent,soln1D.grd.x,ix,1,'cd',postproc.derivwarn);
			dphidr(ix,3,1) =		differentiation(phiCcurrent,soln1D.grd.x,ix,1,'cd',postproc.derivwarn);
			dphidr(ix,4,1) =		differentiation(phiAmBcurrent,soln1D.grd.x,ix,1,'cd',postproc.derivwarn);
		end
		ix = soln1D.simul.nx;
		dphidr(ix,1,1) =			differentiation(phiAcurrent,soln1D.grd.x,ix,1,'bd',postproc.derivwarn);
		dphidr(ix,2,1) =			differentiation(phiBcurrent,soln1D.grd.x,ix,1,'bd',postproc.derivwarn);
		dphidr(ix,3,1) =			differentiation(phiCcurrent,soln1D.grd.x,ix,1,'bd',postproc.derivwarn);
		dphidr(ix,4,1) =			differentiation(phiAmBcurrent,soln1D.grd.x,ix,1,'bd',postproc.derivwarn);
		ix = 1;
		dphidr(ix,1,2) =			differentiation(dphidr(:,1,1),soln1D.grd.x,ix,1,'fd',postproc.derivwarn);
		dphidr(ix,2,2) =			differentiation(dphidr(:,2,1),soln1D.grd.x,ix,1,'fd',postproc.derivwarn);
		dphidr(ix,3,2) =			differentiation(dphidr(:,3,1),soln1D.grd.x,ix,1,'fd',postproc.derivwarn);
		dphidr(ix,4,2) =			differentiation(dphidr(:,4,1),soln1D.grd.x,ix,1,'fd',postproc.derivwarn);
		for ix = 2:soln1D.simul.nx-1
			dphidr(ix,1,2) =		differentiation(dphidr(:,1,1),soln1D.grd.x,ix,1,'cd',postproc.derivwarn);
			dphidr(ix,2,2) =		differentiation(dphidr(:,2,1),soln1D.grd.x,ix,1,'cd',postproc.derivwarn);
			dphidr(ix,3,2) =		differentiation(dphidr(:,3,1),soln1D.grd.x,ix,1,'cd',postproc.derivwarn);
			dphidr(ix,4,2) =		differentiation(dphidr(:,4,1),soln1D.grd.x,ix,1,'cd',postproc.derivwarn);
		end
		ix = soln1D.simul.nx;
		dphidr(ix,1,2) =			differentiation(dphidr(:,1,1),soln1D.grd.x,ix,1,'bd',postproc.derivwarn);
		dphidr(ix,2,2) =			differentiation(dphidr(:,2,1),soln1D.grd.x,ix,1,'bd',postproc.derivwarn);
		dphidr(ix,3,2) =			differentiation(dphidr(:,3,1),soln1D.grd.x,ix,1,'bd',postproc.derivwarn);
		dphidr(ix,4,2) =			differentiation(dphidr(:,4,1),soln1D.grd.x,ix,1,'bd',postproc.derivwarn);
%		postproc.zooming in
		if (postproc.zoomin == 1)
			leftswitch =				1;
			rightswitch =				1;
			ixleft =					1;
			ixright =					soln1D.simul.nx;
			for ix = 1:soln1D.simul.nx
				if ((front.num.R(ix) >= 1E-6*max(front.num.R)) && (leftswitch == 1))
					ixleft =			ix;
					leftswitch =		0;
				end
			end
			for ix = soln1D.simul.nx:-1:1
				if ((front.num.R(ix) >= 1E-6*max(front.num.R)) && (rightswitch == 1))
					ixright =			ix;
					rightswitch =		0;
				end
			end
			if (ixright == ixleft)
				ixright =				ixleft+1;
			end
			set(axl,'xlim',[soln1D.grd.x(ixleft),soln1D.grd.x(ixright)]);
			set(axllin,'xlim',[soln1D.grd.x(ixleft),soln1D.grd.x(ixright)]);
		end
%		including title
		title([postproc.casename,': time is ',num2str(soln1D.grd.t(it))],'Interpreter','none','FontSize',12);
%		plotting collected solutions
		npl = 0;
%		plotting advective element location
		plot(axl,front.r_adv(it)*[1,1],1.25*[-1,1],'-','color',[0.35,0.35,0.35],'linewidth',3); npl=npl+1;
%		filling front widths
		if (postproc.plotfrontwidth == 1)
%			filling analytical front widths
			if (postproc.obtainanalytical == 1)
				fill(axl,	...
				[max(xliml,front.ana.r_f(it)-0.5*front.ana.w_f(it)),	...
				min(xlimr,front.ana.r_f(it)+0.5*front.ana.w_f(it)),		...
				min(xlimr,front.ana.r_f(it)+0.5*front.ana.w_f(it)),		...
				max(xliml,front.ana.r_f(it)-0.5*front.ana.w_f(it))],	...
				[ylims(1),ylims(1),ylims(2),ylims(2)],	...
				[0.35,0.35,0.35],'LineStyle','-.','LineWidth',1.5,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); npl=npl+1;
				fill(axl,	...
				[max(xliml,front.ana.r_f(it)-0.5*front.ana.w_f_approx(it)),	...
				min(xlimr,front.ana.r_f(it)+0.5*front.ana.w_f_approx(it)),	...
				min(xlimr,front.ana.r_f(it)+0.5*front.ana.w_f_approx(it)),	...
				max(xliml,front.ana.r_f(it)-0.5*front.ana.w_f_approx(it))],	...
				[ylims(1),ylims(1),ylims(2),ylims(2)],	...
				[0.35,0.35,0.35],'LineStyle','-.','LineWidth',2,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); npl=npl+1;	
				fill(axl,	...
				[max(xliml,front.ana.r_f_disp(it)-0.5*front.ana.w_f_disp(it)),	...
				min(xlimr,front.ana.r_f_disp(it)+0.5*front.ana.w_f_disp(it)),	...
				min(xlimr,front.ana.r_f_disp(it)+0.5*front.ana.w_f_disp(it)),	...
				max(xliml,front.ana.r_f_disp(it)-0.5*front.ana.w_f_disp(it))],	...
				[ylims(1),ylims(1),ylims(2),ylims(2)],	...
				[0.35,0.35,0.35],'LineStyle','--','LineWidth',1.5,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); npl=npl+1;
				fill(axl,	...
				[max(xliml,front.ana.r_f_disp(it)-0.5*front.ana.w_f_disp_approx(it)),	...
				min(xlimr,front.ana.r_f_disp(it)+0.5*front.ana.w_f_disp_approx(it)),	...
				min(xlimr,front.ana.r_f_disp(it)+0.5*front.ana.w_f_disp_approx(it)),	...
				max(xliml,front.ana.r_f_disp(it)-0.5*front.ana.w_f_disp_approx(it))],	...
				[ylims(1),ylims(1),ylims(2),ylims(2)],	...
				[0.35,0.35,0.35],'LineStyle','--','LineWidth',2,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); npl=npl+1;
				fill(axl,	...
				[max(xliml,front.ana.r_f_stat(it)-0.5*front.ana.w_f_stat(it)),	...
				min(xlimr,front.ana.r_f_stat(it)+0.5*front.ana.w_f_stat(it)),	...
				min(xlimr,front.ana.r_f_stat(it)+0.5*front.ana.w_f_stat(it)),	...
				max(xliml,front.ana.r_f_stat(it)-0.5*front.ana.w_f_stat(it))],	...
				[ylims(1),ylims(1),ylims(2),ylims(2)],	...
				[0.35,0.35,0.35],'LineStyle',':','LineWidth',1.5,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); npl=npl+1;
				fill(axl,[max(xliml,front.ana.r_f_stat(it)-0.5*front.ana.w_f_stat_approx(it)),	...
				min(xlimr,front.ana.r_f_stat(it)+0.5*front.ana.w_f_stat_approx(it)),	...
				min(xlimr,front.ana.r_f_stat(it)+0.5*front.ana.w_f_stat_approx(it)),	...
				max(xliml,front.ana.r_f_stat(it)-0.5*front.ana.w_f_stat_approx(it))],	...
				[ylims(1),ylims(1),ylims(2),ylims(2)],	...
				[0.35,0.35,0.35],'LineStyle',':','LineWidth',2,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); npl=npl+1;
				fill(axl,	...
				[max(xliml,front.num.r_f(ifront.tsaved)-0.5*front.num.w_f(ifront.tsaved)),	...
				min(xlimr,front.num.r_f(ifront.tsaved)+0.5*front.num.w_f(ifront.tsaved)),		...
				min(xlimr,front.num.r_f(ifront.tsaved)+0.5*front.num.w_f(ifront.tsaved)),		...
				max(xliml,front.num.r_f(ifront.tsaved)-0.5*front.num.w_f(ifront.tsaved))],	...
				[ylims(1),ylims(1),ylims(2),ylims(2)],	...
				[0.35,0.35,0.35],'LineStyle','-','LineWidth',0.5,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); npl=npl+1;	
			end
			fill(axl,	...
			[max(xliml,front.num.r_f_orig(ifront.tsaved)-0.5*front.num.w_f_orig(ifront.tsaved,2,1)),	...
			min(xlimr,front.num.r_f_orig(ifront.tsaved)+0.5*front.num.w_f_orig(ifront.tsaved,2,1)),		...
			min(xlimr,front.num.r_f_orig(ifront.tsaved)+0.5*front.num.w_f_orig(ifront.tsaved,2,1)),		...
			max(xliml,front.num.r_f_orig(ifront.tsaved)-0.5*front.num.w_f_orig(ifront.tsaved,2,1))],	...
			[ylims(1),ylims(1),ylims(2),ylims(2)],	...
			[0.35,0.35,0.35],'LineStyle','-','LineWidth',1.0,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); npl=npl+1;	
		end
		npl2retain = npl;
%		plotting numerical GDE terms
		plot(axl,soln1D.grd.x,abs(dphidr(:,1,1)),'-','color',[1.0,0.2,0.2],'linewidth',1); npl=npl+1;
		plot(axl,soln1D.grd.x,abs(dphidr(:,2,1)),'-','color',[0.2,0.2,1.0],'linewidth',1); npl=npl+1;
		plot(axl,soln1D.grd.x,abs(dphidr(:,3,1)),'-','color',[0.2,1.0,0.2],'linewidth',1); npl=npl+1;
		plot(axl,soln1D.grd.x,abs(dphidr(:,4,1)),'-','color',[0.2,0.2,0.2],'linewidth',1); npl=npl+1;
		plot(axl,soln1D.grd.x,abs(dphidr(:,1,2)),'-','color',[1.0,0.2,0.2],'linewidth',2); npl=npl+1;
		plot(axl,soln1D.grd.x,abs(dphidr(:,2,2)),'-','color',[0.2,0.2,1.0],'linewidth',2); npl=npl+1;
		plot(axl,soln1D.grd.x,abs(dphidr(:,3,2)),'-','color',[0.2,1.0,0.2],'linewidth',2); npl=npl+1;
		plot(axl,soln1D.grd.x,abs(dphidr(:,4,2)),'-','color',[0.2,0.2,0.2],'linewidth',2); npl=npl+1;
%		plotting on linear axis
		if (soln1D.geomdom.isradial ~= 0)
			npllin = 0;
%			plotting advective element location
			plot(axllin,front.r_adv(it)*[1,1],1.25*[-1,1],'-','color',[0.35,0.35,0.35],'linewidth',3); npllin=npllin+1;
%			plotting analytical front locations
			if (postproc.obtainanalytical == 1)
				plot(axllin,front.ana.r_f(it)*[1,1],1.25*[-1,1],'-.','color',[0.35,0.35,0.35],'linewidth',3); 
				npllin=npllin+1;
				plot(axllin,front.ana.r_f_disp(it)*[1,1],1.25*[-1,1],'--','color',[0.35,0.35,0.35],'linewidth',3); 
				npllin=npllin+1;
				plot(axllin,front.ana.r_f_stat(it)*[1,1],1.25*[-1,1],':','color',[0.35,0.35,0.35],'linewidth',3); 
				npllin=npllin+1;
			end
%			filling front widths
			if (postproc.plotfrontwidth == 1)
%				filling analytical front widths
				if (postproc.obtainanalytical == 1)
					fill(axllin,	...
					[max(xliml,front.ana.r_f(it)-0.5*front.ana.w_f(it)),	...
					min(xlimr,front.ana.r_f(it)+0.5*front.ana.w_f(it)),		...
					min(xlimr,front.ana.r_f(it)+0.5*front.ana.w_f(it)),		...
					max(xliml,front.ana.r_f(it)-0.5*front.ana.w_f(it))],	...
					[ylims(1),ylims(1),ylims(2),ylims(2)],	...
					[0.35,0.35,0.35],'LineStyle','-.','LineWidth',1.5,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); 
					npllin=npllin+1;
					fill(axllin,	...
					[max(xliml,front.ana.r_f(it)-0.5*front.ana.w_f_approx(it)),	...
					min(xlimr,front.ana.r_f(it)+0.5*front.ana.w_f_approx(it)),	...
					min(xlimr,front.ana.r_f(it)+0.5*front.ana.w_f_approx(it)),	...
					max(xliml,front.ana.r_f(it)-0.5*front.ana.w_f_approx(it))],	...
					[ylims(1),ylims(1),ylims(2),ylims(2)],	...
					[0.35,0.35,0.35],'LineStyle','-.','LineWidth',2,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); 
					npllin=npllin+1;	
					fill(axllin,	...
					[max(xliml,front.ana.r_f_disp(it)-0.5*front.ana.w_f_disp(it)),	...
					min(xlimr,front.ana.r_f_disp(it)+0.5*front.ana.w_f_disp(it)),	...
					min(xlimr,front.ana.r_f_disp(it)+0.5*front.ana.w_f_disp(it)),	...
					max(xliml,front.ana.r_f_disp(it)-0.5*front.ana.w_f_disp(it))],	...
					[ylims(1),ylims(1),ylims(2),ylims(2)],	...
					[0.35,0.35,0.35],'LineStyle','--','LineWidth',1.5,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); 
					npllin=npllin+1;		
					fill(axllin,	...
					[max(xliml,front.ana.r_f_disp(it)-0.5*front.ana.w_f_disp_approx(it)),	...
					min(xlimr,front.ana.r_f_disp(it)+0.5*front.ana.w_f_disp_approx(it)),	...
					min(xlimr,front.ana.r_f_disp(it)+0.5*front.ana.w_f_disp_approx(it)),	...
					max(xliml,front.ana.r_f_disp(it)-0.5*front.ana.w_f_disp_approx(it))],	...
					[ylims(1),ylims(1),ylims(2),ylims(2)],	...
					[0.35,0.35,0.35],'LineStyle','--','LineWidth',2,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); 
					npllin=npllin+1;		
					fill(axllin,	...
					[max(xliml,front.ana.r_f_stat(it)-0.5*front.ana.w_f_stat(it)),	...
					min(xlimr,front.ana.r_f_stat(it)+0.5*front.ana.w_f_stat(it)),	...
					min(xlimr,front.ana.r_f_stat(it)+0.5*front.ana.w_f_stat(it)),	...
					max(xliml,front.ana.r_f_stat(it)-0.5*front.ana.w_f_stat(it))],	...
					[ylims(1),ylims(1),ylims(2),ylims(2)],	...
					[0.35,0.35,0.35],'LineStyle',':','LineWidth',1.5,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); 
					npllin=npllin+1;				
					fill(axllin,[max(xliml,front.ana.r_f_stat(it)-0.5*front.ana.w_f_stat_approx(it)),	...
					min(xlimr,front.ana.r_f_stat(it)+0.5*front.ana.w_f_stat_approx(it)),	...
					min(xlimr,front.ana.r_f_stat(it)+0.5*front.ana.w_f_stat_approx(it)),	...
					max(xliml,front.ana.r_f_stat(it)-0.5*front.ana.w_f_stat_approx(it))],	...
					[ylims(1),ylims(1),ylims(2),ylims(2)],	...
					[0.35,0.35,0.35],'LineStyle',':','LineWidth',2,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); 
					npllin=npllin+1;		
					fill(axllin,	...
					[max(xliml,front.num.r_f(ifront.tsaved)-0.5*front.num.w_f(ifront.tsaved)),	...
					min(xlimr,front.num.r_f(ifront.tsaved)+0.5*front.num.w_f(ifront.tsaved)),		...
					min(xlimr,front.num.r_f(ifront.tsaved)+0.5*front.num.w_f(ifront.tsaved)),		...
					max(xliml,front.num.r_f(ifront.tsaved)-0.5*front.num.w_f(ifront.tsaved))],	...
					[ylims(1),ylims(1),ylims(2),ylims(2)],	...
					[0.35,0.35,0.35],'LineStyle','-','LineWidth',0.5,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); 
					npllin=npllin+1;	
				end
				fill(axllin,	...
				[max(xliml,front.num.r_f_orig(ifront.tsaved)-0.5*front.num.w_f_orig(ifront.tsaved,2,1)),	...
				min(xlimr,front.num.r_f_orig(ifront.tsaved)+0.5*front.num.w_f_orig(ifront.tsaved,2,1)),		...
				min(xlimr,front.num.r_f_orig(ifront.tsaved)+0.5*front.num.w_f_orig(ifront.tsaved,2,1)),		...
				max(xliml,front.num.r_f_orig(ifront.tsaved)-0.5*front.num.w_f_orig(ifront.tsaved,2,1))],	...
				[ylims(1),ylims(1),ylims(2),ylims(2)],	...
				[0.35,0.35,0.35],'LineStyle','-','LineWidth',1.0,'EdgeColor',[0.35,0.35,0.35],'FaceAlpha',0.01); 
				npllin=npllin+1;	
			end
			npllin2retain = npllin;
%			plotting numerical GDE terms
			plot(axllin,soln1D.grd.x,abs(dphidr(:,1,1)),'-','color',[1.0,0.2,0.2],'linewidth',1); npllin=npllin+1;
			plot(axllin,soln1D.grd.x,abs(dphidr(:,2,1)),'-','color',[0.2,0.2,1.0],'linewidth',1); npllin=npllin+1;
			plot(axllin,soln1D.grd.x,abs(dphidr(:,3,1)),'-','color',[0.2,1.0,0.2],'linewidth',1); npllin=npllin+1;
			plot(axllin,soln1D.grd.x,abs(dphidr(:,4,1)),'-','color',[0.2,0.2,0.2],'linewidth',1); npllin=npllin+1;
			plot(axllin,soln1D.grd.x,abs(dphidr(:,1,2)),'-','color',[1.0,0.2,0.2],'linewidth',2); npllin=npllin+1;
			plot(axllin,soln1D.grd.x,abs(dphidr(:,2,2)),'-','color',[0.2,0.2,1.0],'linewidth',2); npllin=npllin+1;
			plot(axllin,soln1D.grd.x,abs(dphidr(:,3,2)),'-','color',[0.2,1.0,0.2],'linewidth',2); npllin=npllin+1;
			plot(axllin,soln1D.grd.x,abs(dphidr(:,4,2)),'-','color',[0.2,0.2,0.2],'linewidth',2); npllin=npllin+1;
		end
		pause(postproc.timepausevid);
		movframecurr =     getframe(figl);
		writeVideo(phimovvid,movframecurr);
		for ii = 1:npl-npl2retain
			lastline = get(axl,'children');
			delete(lastline(1));
		end
		if (soln1D.geomdom.isradial ~= 0)
			for ii = 1:npllin-npllin2retain
				lastline = get(axllin,'children');
				delete(lastline(1));
			end
		end
	catch
	end
end
close(figl);
close(phimovvid);